chore: remove downlevel-dts for performance improvement purposes
aws/jsii-compiler pull request #1474
Opened 2024-11-12 05:01 UTC by HBobertz

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

2024-11-12 05:13 UTC, HBobertz commented
Getting test failures I'm not getting locally. I'll figure that out

2024-11-12 07:26 UTC, mrgrain commented
Let's probably not make this a `chore` but a `fix`.

2024-11-12 22:30 UTC, mrgrain commented on fixtures/@scope/jsii-calc-base/lib/index.ts
> +export * as deep from './deep';
```suggestion
export * as deep from './deep';

```

2024-11-12 22:32 UTC, mrgrain commented on src/compiler.ts
> +export const TYPES_COMPAT = '.types-compat';
```suggestion
```

2024-11-12 22:32 UTC, mrgrain commented on test/compiler.test.ts
> +import { Compiler, TYPES_COMPAT } from '../src/compiler';
```suggestion
import { Compiler } from '../src/compiler';
```

2024-11-12 22:33 UTC, mrgrain commented on test/compiler.test.ts
> +import { Compiler, TYPES_COMPAT } from '../src/compiler';
Please adjust the tests in this file (and possibly code)
`TYPES_COMPAT` should not be emitted anymore.

2024-11-12 22:35 UTC, mrgrain requested changes
small changes left

2024-11-13 15:21 UTC, mrgrain approved these changes

2024-11-13 15:29 UTC, merged